/* DO NOT EDIT THIS FILE - it is machine generated */
#include "seminar_android_testndk_MainActivity.h"
/* Header for class seminar_android_testndk_MainActivity */

JNIEXPORT jstring JNICALL Java_seminar_android_testndk_MainActivity_getStringFromNative
  (JNIEnv * env, jobject obj)
{
  return (*env)->NewStringUTF(env, "Hello from JNI !");
}

